=== qthequartermasterman/reign-of-the-judges/docs/schemas/event.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "event.json",
    "title": "Event",
    "description": "An event in the scriptures.",
    "type": "object",
    "properties": {
        "id": {
            "description": "The unique identifier of the event.",
            "type": "string",
            "format": "uuid"
        },
        "name": {
            "description": "The name of the event.",
            "type": "string"
        },
        "description": {
            "description": "A description of the event.",
            "type": "string"
        },
        "sources": {
            "description": "The sources that describe the event.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "date": {
            "description": "The date of the event, if it occurred at a specific time, or the date of the event's beginning, if it was a period of time.",
            "$ref": "date.json"
        },
        "end_date": {
            "description": "The date of the event's end, if it was a period of time.",
            "$ref": "date.json"
        },
        "location": {
            "description": "The location of the event.",
            "type": "object",
            "properties": {
                "name": {
                    "description": "The name of the location.",
                    "type": "string"
                },
                "description": {
                    "description": "A description of the location.",
                    "type": "string"
                }
            }
        },
        "participants": {
            "description": "The participants in the event.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "relative_events": {
            "description": "Events that this event is definitely after or before.",
            "type": "object",
            "properties": {
                "before": {
                    "description": "Events that this event is definitely before.",
                    "type": "array",
                    "items": {
                        "#ref": "event.json"
                    }
                },
                "after": {
                    "description": "Events that this event is definitely after.",
                    "type": "array",
                    "items": {
                        "#ref": "event.json"
                    }
                }
            }
        }
        
    }
}

=== qthequartermasterman/reign-of-the-judges/docs/events/alma/10/amulek-receives-an-angel.json
{
    "name": "Amulek Receives an Angel",
    "description": "Amulek receives an angel who tells him to receive Alma into his house.",
    "sources": ["Alma 10:4-10"],
    "date": {
        "calendar_system": "reign-of-the-judges",
        "year": 10,
        "day": 4,
        "month": 7
    },
    "participants": ["Amulek", "Alma", "Angel"],
    "location": {
        "name": "Ammonihah"
    }
}

=== qthequartermasterman/reign-of-the-judges/docs/events/alma/4/wickedness-in-the-church.json
{
  "name": "Wickedness in the Church",
  "description": "In the eighth year of the reign of the judges, there began to be great contentions among the people of the church; yea, there were envyings, and strife, and malice, and persecutions, and pride, even to exceed the pride of those who did not belong to the church of God.",
  "sources": ["Alma 4:10"],
  "date": {
    "calendar_system": "reign-of-the-judges",
    "year": 8,
    "miscellaneous": "end"
  },
  "participants": ["Nephites", "Saints"],
  "location": {
    "name": "Land of Zarahemla"
  },
  "relative_events": {
    "after": ["docs/events/alma/4/contention-in-the-church.json"]
  }
}

=== qthequartermasterman/reign-of-the-judges/docs/events/alma/16/continual-peace.json
{
    "name": "Continual Peace",
    "description": "Lamanites did not attack the People of Nephi, and Alma and Amulek preach throughout the land of the Nephites.",
    "sources": ["Alma 16:12-21"],
    "date": {
        "calendar_system": "reign-of-the-judges",
        "year": 11
    },
    "end_date": {
        "calendar_system": "reign-of-the-judges",
        "year": 14,
        "miscellaneous": "end"
    },
    "participants": [
        "Lamanites",
        "People of Nephi",
        "Alma the Younger",
        "Amulek"
    ],
    "location": {
        "name": "Land of Zarahemla"
    },
    "relative_events": {
        "after": [
            "./destruction-of-ammonihah.json",
            "./repel-the-lamanites.json"
        ]
    }
}

=== qthequartermasterman/reign-of-the-judges/docs/events/alma/17/sons-of-mosiah-depart.json
{
  "name": "Sons of Mosiah Depart to Preach to the Lamanites",
  "description": "The sons of Mosiah depart to preach to the Lamanites.",
  "sources": ["Alma 17:1-2"],
  "date": {
    "calendar_system": "reign-of-the-judges",
    "year": 1
  },
  "location": {
    "name": "Zarahemla"
  },
  "participants": ["Ammon", "Aaron", "Omner", "Himni"]
}

=== qthequartermasterman/reign-of-the-judges/docs/events/alma/16/destruction-of-ammonihah.json
{
    "name": "Destruction of Ammonihah (Desolation of Nehors)",
    "description": "The Lamanites suddenly destroy the city of Ammonihah after years of peace.",
    "sources": ["Alma 16:1-3,9-10"],
    "date": {
        "calendar_system": "reign-of-the-judges",
        "year": 11,
        "month":2,
        "day": 5
    },
    "participants": [
        "Lamanites",
        "People of Ammonihah",
        "Captives of Noah"
    ],
    "location": {
        "name": "Ammonihah and Noah"
    }
}

=== qthequartermasterman/reign-of-the-judges/docs/events/alma/2/battle-of-river-sidon.json
{
    "name": "Battle of River Sidon",
    "description": "Lamanite and Amlicite troops (\"numerous as the sands of the sea\") descend upon Nephite forces as they cross the River Sidon. Alma and Amlici contend face to face with the sword. Alma cries to the Lord for mercy. They prevail against the Lamanites. Many die while fleeing, and their bones heap upon the earth.",
    "sources": ["Alma 2:28-38"],
    "date": {
        "calendar_system": "reign-of-the-judges",
        "year": 5
    },
    "participants": ["Alma", "Amlici", "Amlicites", "Lamanites", "Nephites"],
    "relative_events": {
        "after": ["docs/events/alma/2/spying-on-amlicite-camp.json"]
    },
    "location": {
        "name": "River Sidon"
    }
    
}

=== qthequartermasterman/reign-of-the-judges/docs/events/alma/16/zoram-asks-alma.json
{
    "name": "Zoram asks Alma for revelation about the location of the Lamanite armies",
    "description": "Zoram asks Alma for revelation about the location of the Lamanite armies.",
    "sources": [
        "Alma 16:4-6"
    ],
    "date": {
        "calendar_system": "reign-of-the-judges",
        "year": 11
    },
    "participants": [
        "Zoram, Chief Captain of the Nephite armies",
        "Alma the Younger"
    ],
    "relative_events": {
        "after": [
            "./destruction-of-ammonihah.json"
        ]
    }
}

=== qthequartermasterman/reign-of-the-judges/docs/events/alma/8/alma-departs-for-melek.json
{
    "name": "Alma Departs for Melek",
    "description": "Alma departs from the land of Zarahemla and takes his journey over into the land of Melek, on the west of the river Sidon, on the west by the borders of the wilderness.",
    "sources": ["Alma 8:3"],
    "date": {
        "calendar_system": "reign-of-the-judges",
        "year": 10
    },
    "participants": ["Alma"],
    "location": {
        "name": "Land of Melek",
        "description": "On the west of the river Sidon, on the west by the borders of the wilderness."
    }
}
