=== qthequartermasterman/reign-of-the-judges/docs/schemas/event.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "event.json",
    "title": "Event",
    "description": "An event in the scriptures.",
    "type": "object",
    "properties": {
        "id": {
            "description": "The unique identifier of the event.",
            "type": "string",
            "format": "uuid"
        },
        "name": {
            "description": "The name of the event.",
            "type": "string"
        },
        "description": {
            "description": "A description of the event.",
            "type": "string"
        },
        "sources": {
            "description": "The sources that describe the event.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "date": {
            "description": "The date of the event, if it occurred at a specific time, or the date of the event's beginning, if it was a period of time.",
            "$ref": "date.json"
        },
        "end_date": {
            "description": "The date of the event's end, if it was a period of time.",
            "$ref": "date.json"
        },
        "location": {
            "description": "The location of the event.",
            "type": "object",
            "properties": {
                "name": {
                    "description": "The name of the location.",
                    "type": "string"
                },
                "description": {
                    "description": "A description of the location.",
                    "type": "string"
                }
            }
        },
        "participants": {
            "description": "The participants in the event.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "relative_events": {
            "description": "Events that this event is definitely after or before.",
            "type": "object",
            "properties": {
                "before": {
                    "description": "Events that this event is definitely before.",
                    "type": "array",
                    "items": {
                        "#ref": "event.json"
                    }
                },
                "after": {
                    "description": "Events that this event is definitely after.",
                    "type": "array",
                    "items": {
                        "#ref": "event.json"
                    }
                }
            }
        }
        
    }
}

=== qthequartermasterman/reign-of-the-judges/docs/events/alma/2/amlicite-rebellion.json
{
    "name": "Amlicite Rebellion Begins",
    "description": "The Amlicites rebel against the Nephites and seek to establish a king. The Amlicite rebellion begins. The amlicites consecreate Amlici as their king. Nephites and Amlicites appoint captains, higher captains, and chief captains and prepare every weapon of war. ",
    "sources": ["Alma 2:8-14"],
    "date": {
        "calendar_system": "reign-of-the-judges",
        "year": 5
    },
    "participants": ["Amlici", "Amlicites", "Nephites"],
    "relative_events": {
        "after": ["docs/events/alma/2/amlici-election.json"]
    }
}

=== qthequartermasterman/reign-of-the-judges/docs/events/alma/4/alma-dedicates-himself-to-governing-the-church.json
{
    "name": "Alma dedicates himself to governing the church",
    "description": "Alma delivers up the judgment-seat to Nephihah and confines himself wholly to the high priesthood of the holy order of God, to the testimony of the word, according to the spirit of revelation and prophecy.",
    "sources": ["Alma 4:20"],
    "date": {
        "calendar_system": "reign-of-the-judges",
        "year": 9,
        "miscellaneous": "commencement"
    },
    "participants": ["Alma", "Nephihah"],
    "relative_events": {
        "after": ["docs/events/alma/4/nephihah-appointment.json"]
    }
}

=== qthequartermasterman/reign-of-the-judges/docs/events/alma/3/second-battle-of-hill-amnihu.json
{
    "name": "Second Battle of Hill Amnihu",
    "description": "Nephites drive Amlicites and Lamanites out of the land of Zarahemla one final time. The Amlicite Rebellion effectively ends.",
    "sources": ["Alma 3:20-24"],
    "date": {
        "calendar_system": "reign-of-the-judges",
        "year": 5
    },
    "participants": ["Nephites", "Amlicites", "Lamanites"],
    "relative_events": {
        "after": ["docs/events/alma/3/nephites-bury-dead.json"]
    },
    "location": {
        "name": "Hill Amnihu"
    }
    
}

=== qthequartermasterman/reign-of-the-judges/docs/events/alma/1/nehor-gideon.json
{
    "name": "Nehor contends with Gideon",
    "description": "Nehor contends with Gideon, murdering him with the sword.",
    "date": {
        "year": 1,
        "calendar_system": "reign-of-the-judges"
    },
    "location": {
        "name": "Zarahemla"
    },
    "participants": [
        "Nehor",
        "Gideon"
    ],
    "relative_events": {
        "before": [
            {
                "$ref": "./nehor-trial.json"
            }
        ]
    },
    "sources": ["Alma 1:7-9"]
}

=== qthequartermasterman/reign-of-the-judges/docs/events/alma/3/amlicites-mark-foreheads.json
{
    "name": "Amlicites mark their foreheads",
    "description": "Amlicites mark their heads with red, fulfilling prophecy",
    "sources": ["Alma 3:4-19"],
    "date": {
        "calendar_system": "reign-of-the-judges",
        "year": 5
    },
    "participants": ["Amlicites"],
    "relative_events": {
        "after": ["docs/events/alma/3/nephites-bury-dead.json"]
    }
}

=== qthequartermasterman/reign-of-the-judges/docs/events/alma/4/alma-fights-iniquity.json
{
    "name": "Alma fights iniquity within the church",
    "description": "Alma saw the wickedness of the church, and he saw also that the example of the church began to lead those who were unbelievers on from one piece of iniquity to another, thus bringing on the destruction of the people.",
    "sources": ["Alma 4:11"],
    "date": {
        "calendar_system": "reign-of-the-judges",
        "year": 9,
        "miscellaneous": "commencement"
    },
    "participants": ["Alma", "Saints"]

}

=== qthequartermasterman/reign-of-the-judges/docs/events/alma/50/pahoran_1-appointment.json
{
    "name": "Pahron~1~ appointed Chief Judge",
    "description": "Pahoran~1~ appointed Chief Judge and Governor with an oath and sacred ordinance.",
    "location": {
        "name": "Zarahemla"
    },
    "participants": [
        "Pahoran~1~"
    ],
    "date": {
        "year": 24,
        "calendar_system": "reign-of-the-judges",
        "miscellaneous": "end"
    },
    "sources": [
        "Alma 50:39-40"
    ]
}

=== qthequartermasterman/reign-of-the-judges/docs/events/alma/2/amlici-appears.json
{
    "name": "Amlici's Campaign",
    "description": "Amlici, a Nehor, appears and begins to stir up contention among the people. He aspires to become a king and destroy the Church and generates a great political movement among the Nephites",
    "date": {
        "calendar_system": "reign-of-the-judges",
        "year": 5,
        "miscellaneous": "commencement"
    },
    "participants": ["Amlici"],
    "sources":["Alma 2:1-5"]
}
